# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc3ea3c9f60f115c2a477c115e53041ba02623f809d2f292bfbdd9e80e06603cb2d8d46b94bb5fc6f758abbfb13b397e665cc028d564518f8b38252f00232d20

test:
  secret_key_base: 5c842a06dce815ebb6afa3c49d377e99add5e39424de218f005b691100f8d6d66ceea7bc96f5e9119ea3ee7977ecc24336f6a9599f8e7c9c2b2de443f445ee3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
